### PR TITLE
keep hashtag and urls

### PR DESCRIPTION
**Pull request by phoet**
so you guys still have all the relevant contexts! /cc @celsodantas @kurtfunai

### CODE REVIEW

**Comment by kurtfunai** [comment]
Cant merge!!!!

**Comment by celsodantas** [comment]
I removed the bare `curl` and I'm using https://github.com/shvets/google-translate now. Everything should work now. 

I guess ....  =P

**Comment by celsodantas** [comment]
here is the new code https://github.com/celsodantas/phoetbot/blob/master/app.rb#L23-L24

**Comment by phoet** [comment]
\o/

**Pull request closed without merging**
